services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./:/var/www/html


